<?php

namespace backend\controllers;

use Yii;
use backend\models\TbDepartaments;
use backend\models\TbDepartamentoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;


class RelatoriodepartamentoController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $searchModel = new TbDepartamentoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionGenpdf()
    {

        $searchModel = new TbDepartamentoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $content = $this->renderPartial('gen-pdf', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
            'content' =>$content,
            'options' => [
                'title' => 'Privacy Policy - Krajee.com',
                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
            'methods' => [
                'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();

    }


}
